version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./env/app/Dockerfile
    volumes:
      - ./app:/app
  app-debug:
    build:
      context: .
      dockerfile: ./env/app-debug/Dockerfile
    volumes:
      - ./app:/app